<?php
/** @var \Astound\ContactUs\Block\ContactForm $block */
?>
<?php $this->getLayout()->getBlock('breadcrumbs')->toHtml(); ?>
<div class="contact-page">
    <div class="row">
        <div class="column">
            <h1 class="contact-page-title">Contact Us</h1>
            <div class="contact-page-content">
                <?= $block->getChildHtml('astound.contact.us.main.content') ?>
            </div>
            <div class="row">
                <div class="column medium-6 large-4">
                    <form class="contact-page-form"
                          action="<?= $block->escapeUrl($block->getFormAction()) ?>"
                          id="contact-form"
                          method="post"
                          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
                          data-mage-init='{"validation":{}}'>
                        <?php echo $block->getBlockHtml('formkey')?>
                        <h3>
                            <?= $block->escapeHtml(__('Write Us')) ?>
                        </h3>
                        <div class="contact-page-field">
                            <label class="required" for="name"><?= $block->escapeHtml(__('Name')) ?></label>
                            <input name="name"
                                   id="name"
                                   title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                                   value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>"
                                   class="required-entry"
                                   type="text"
                                   data-validate="{required:true}"/>
                        </div>
                        <div class="contact-page-field">
                            <label class="required" for="email"><?= $block->escapeHtml(__('Email')) ?></label>
                            <input name="email"
                                   id="email"
                                   title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                                   value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>"
                                   class="required-entry"
                                   type="email"
                                   data-validate="{required:true, 'validate-email':true}"/>
                        </div>
                        <div class="contact-page-field">
                            <label for="telephone"><?= $block->escapeHtml(__('Phone Number')) ?></label>
                            <input name="telephone"
                                   id="telephone"
                                   title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                                   value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>"
                                   type="text" />
                        </div>

                        <?php if (!empty($block->getAvailableSubjects())): ?>
                            <div class="contact-page-field">
                                <label for="subject" class="required"><?= $block->escapeHtml(__('Subject')) ?></label>
                                <select id="subject" name="subject" data-validate="{required:true}">
                                    <option value=""><?= $block->escapeHtml(__('Please select subject')) ?></option>
                                    <?php foreach ($block->getAvailableSubjects() as $index => $subject): ?>
                                        <?php $index++ ?>
                                        <option value="<?= $block->escapeHtml($index) ?>"
                                            <?php if ($index == $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('subject'))): ?> selected="selected"<?php endif; ?>>
                                            <?= $block->escapeHtml($subject) ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        <?php endif; ?>

                        <div class="contact-page-field">
                            <label class="required" for="comment"><?= $block->escapeHtml(__('Comment')) ?></label>
                            <textarea name="comment"
                                      id="comment"
                                      title="<?= $block->escapeHtmlAttr(__('Comment')) ?>"
                                      class="required-entry"
                                      cols="5" rows="3"
                                      data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                        </div>
                        <?= $block->getChildHtml('form.additional.info') ?>
                        <div class="contact-page-actions">
                            <input type="hidden" name="hideit" id="hideit" value="" />
                            <button type="submit"
                                    title="<?= $block->escapeHtmlAttr(__('Submit')) ?>"
                                    class="contact-page-submit">
                                <?= $block->escapeHtml(__('Submit')) ?>
                            </button>
                        </div>
                    </form>
                </div>
                <div class="column medium-6 large-7 large-offset-1">
                    <div class="contact-page-info">
                        <?= $block->getChildHtml('form.additional.info.extra') ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
